### ISSUE TITLE
SARIF Explorer does not handle multiple issues with the same line and column number well

### ISSUE THREAD

**Issue by markhermelinggt** [Microsoft/sarif-vscode-extension#112]
I have a SARIF file with multiple findings on a single line at the same column. When I double click the first time on an issue on line x, column, then the SARIF explorer updates. However, when I double click on another issue on the same line and column, then the explorer does not update.

VSCode Version: 1.21.1
OS Version: MacOS 10.14
Steps to Reproduce:

Have a SARIF file with several issues with the same line and column number
I have a video with the issue demonstrated, but it won't let me attach. Happy to share video and SARIF file via another method.

SARIF file was exported from CodeSonar.

Does this issue occur when all extensions are disabled?: Irrelevant

**Comment by rscrivens** [comment]
Thanks for the bug, I think this is due to a limitation of how we're detecting when an issue is selected. We use CodeActions that gets triggered when a location gets focus that we have a diagnostic at. But we don't have a way to determine which result if there are two at the same location. I don't think there is a way to get the currently selected diagnostic in the problems view. I'll open an issue against vscode to see if they'll be willing to add something to their api to allow us to get this information.

I'll also look into trying to implement something so the ResultsList in the Sarif Explorer is able to handle this scenario.

**Comment by rscrivens** [comment]
The ResultsList in the Sarif Explorer allows you to navigate to different results on the same line. 
![samelinedemo](https://user-images.githubusercontent.com/34690530/52008321-421da480-2485-11e9-91c3-49906d711228.gif)

**Comment by rscrivens** [comment]
closing out this issue. Reopen if using the results list as shown above doesn't work for your scenario.
