### ISSUE TITLE
Unstable selection when multiple Results share the same line of code

### ISSUE THREAD

**Issue by jeffersonking** [microsoft/sarif-vscode-extension#406]
As quoted from @niroshan via @eddynaka:

> When selecting an issue in the plugin and there are multiple issues for the same line the plugin may warp you to one of the other issues and you end up losing your place in the result view and you also lose the detail view of the issue.

> This one is weird: When selecting an issue in the result view the selection in the source file is in a flux and can change while making an edit which causes the wrong piece of code to be edited.  Thankfully VSCode has an undo function so the damage can be rolled back.

**Comment by jeffersonking** [comment]
Due to the way VS Code processes are split (UI vs extension), there is known possibility of a 2-way sync issues with state (in this case the Result selection). However, while designing this area, these types of issues were not frequent (at least not for us). Also at the time of design, we were also unsure of the frequency in the real world of overlapping results.

I recreated a very basic SARIF log with 3 results on the same line (let's call these A B C), and 1 result on another line (let's call this D). The most similar behavior I could reproduce, is when you change your selection D to C, the selection jumps to A. The selection remains stable while within A, B, and C.

@niroshan Does this represent what you experienced? Does this encompass all of what you are seeing? Thanks!

**Comment by jeffersonking** [comment]
To respond to the issue of "selection... change while making an edit", @niroshan, can you help us reproduce that situation? Thanks!

**Comment by kuriboshi** [comment]
> I recreated a very basic SARIF log with 3 results on the same line (let's call these A B C), and 1 result on another line (let's call this D). The most similar behavior I could reproduce, is when you change your selection D to C, the selection jumps to A. The selection remains stable while within A, B, and C. To generalize, when entering a set of overlapping results, the selection jumps to the first of the group.

Yes, this describes the behavior pretty well.  I've attached a short screen recording to illustrate the problem.  It's especially noticeable in the "Rules" tab in the SARIF viewer.  Let's say I want to fix problems of a specific type and I go through them one by one.  This is very difficult if there are other errors on the same line since the selection in the SARIF Viewer is lost.

https://user-images.githubusercontent.com/9445936/139812010-1b68ee1a-8c3a-4e80-be23-dbdfe5cdf045.mov

**Comment by kuriboshi** [comment]
For the "jumping selection" problem I think it's related and it happens when I click somewhere in the line with the intention of editing that line. Here is another screen recording to illustrate what happens. I click after the parenthesis meaning to insert a newline there. The selection changes and the newline I typed deletes the entire line. In order to make edits I have to be very careful and wait for the selection to settle down before making any changes.

https://user-images.githubusercontent.com/9445936/139813727-0ece85bb-271e-455a-8e4c-ac7615043a4c.mov

Hope this helps clarifying the problem.
